# ID: npow
# Makefile for CS240 Assignment 1 Problem 6
CC=g++
CFLAGS=-Wall

all: intersection threshold pertinent

intersection: intersection.cc
	$(CC) $(CFLAGS) intersection.cc -o intersection

threshold: threshold.cc
	$(CC) $(CFLAGS) threshold.cc -o threshold

pertinent: pertinent.cc
	$(CC) $(CFLAGS) pertinent.cc -o pertinent
