
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Sun Nov 13 23:28:56 EST 2005
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int ADDOP = 25;
  public static final int RELOP = 26;
  public static final int ELSE = 14;
  public static final int STRUCT = 21;
  public static final int INT = 28;
  public static final int INSIGN = 18;
  public static final int OR = 10;
  public static final int CHAR = 29;
  public static final int SEMI = 2;
  public static final int IN = 16;
  public static final int WHILE = 15;
  public static final int CLOSEB = 6;
  public static final int NOT = 9;
  public static final int EQOP = 27;
  public static final int PERIOD = 22;
  public static final int RETURN = 11;
  public static final int OUTSIGN = 19;
  public static final int IF = 12;
  public static final int ID = 31;
  public static final int MULOP = 24;
  public static final int TYPE = 23;
  public static final int COMMA = 7;
  public static final int EOF = 0;
  public static final int ELSEIF = 13;
  public static final int OPENP = 3;
  public static final int error = 1;
  public static final int ASSIGN = 20;
  public static final int BOOL = 30;
  public static final int OUT = 17;
  public static final int AMPERSAND = 8;
  public static final int CLOSEP = 4;
  public static final int OPENB = 5;
}

