# ID: npow
# Makefile for CS240 Assignment 2 Problem 5
CC=g++
CFLAGS=-Wall

all: ord2bin bin2ord

ord2bin: ord2bin.cc
	$(CC) $(CFLAGS) ord2bin.cc -o ord2bin

bin2ord: bin2ord.cc
	$(CC) $(CFLAGS) bin2ord.cc -o bin2ord
